language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coverage

script:
  - python -m coverage run -m unittest discover

after_success:
  - coveralls

notifications:
  email:
    - d.mentiplay@gmail.com
