language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install black coverage coveralls isort mypy

script:
  - python -m coverage run -m unittest discover
  - isort --check-only -rc
  - black --check --skip-string-normalization .
  - mypy --no-strict-optional phantomconfig tests

after_success:
  - coveralls

notifications:
  email:
    - d.mentiplay@gmail.com
